name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clean Workspace
      - name: Clean workspace
        run: |
          rm -rf *

      # Step 2: Checkout Repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: N4si/DevSecOps-Project
          ref: main

      # Step 3: Setup Tools
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 4: SonarQube Analysis
      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
          -Dsonar.projectName=Netflix \
          -Dsonar.projectKey=Netflix

      # Step 5: Quality Gate
      - name: Quality Gate
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }} "$SONAR_HOST_URL/api/qualitygates/project_status?projectKey=Netflix" \
          | grep '"status":"OK"' || exit 1

      # Step 6: Install Dependencies
      - name: Install Dependencies
        run: npm install
